export const LoadingKeys = {
    ADMIN_MENU: {
        SEARCH: 'admin-menu-search',
        SEARCH_BY_ID: 'admin-menu-search-by-id',
        CREATE: 'admin-menu-create',
        UPDATE: 'admin-menu-update',
        DELETE: 'admin-menu-delete'
    },
    USER: {
        LOGIN: {
            CREDENTIAL: 'user-login-credential',
            OAUTH: {
                GOOGLE: 'user-login-oauth-google',
                FACEBOOK: 'user-login-oauth-facebook'
            }
        }
    },
    PRESCRIPTION: {
        GET_DRAFT: 'prescription-get-draft',
        SAVE_DRAFT: 'prescription-save-draft',
        ISSUE: 'prescription-issue',
        CANCEL: 'prescription-cancel',
        CDS_CHECK: 'prescription-cds-check',
        COST_ESTIMATE: 'prescription-cost-estimate',
        RECENT: 'prescription-recent',
        FAVORITES: 'prescription-favorites',
        TEMPLATES: 'prescription-templates'
    },
    MEDICINE: {
        SEARCH: 'medicine-search'
    },
    TREATMENT: {
        SUMMARY: 'treatment-summary',
        STATS: 'treatment-stats',
        ALERTS: 'treatment-alerts',
        ACKNOWLEDGE: 'treatment-acknowledge',
        TIMELINE: 'treatment-timeline',
        ORDERS: 'treatment-orders',
        ORDER_UPDATE: 'treatment-order-update',
        MEDICATIONS: 'treatment-medications',
        MEDICATION_UPDATE: 'treatment-medication-update',
        PROCEDURES: 'treatment-procedures',
        ADD_PROCEDURE: 'treatment-add-procedure',
        LABS: 'treatment-labs',
        IMAGING: 'treatment-imaging',
        NOTES: 'treatment-notes',
        ADD_NOTE: 'treatment-add-note'
    },
    SURGERY: {
        STATS: 'surgery-stats',
        TRENDS: 'surgery-trends',
        ALERTS: 'surgery-alerts',
        ACKNOWLEDGE: 'surgery-acknowledge',
        CASES_SEARCH: 'surgery-cases-search',
        CASE_DETAIL: 'surgery-case-detail',
        CASE_CANCEL: 'surgery-case-cancel',
        ROOMS: 'surgery-rooms',
        ROOM_STATUS: 'surgery-room-status',
        CHECKLIST_ITEM: 'surgery-checklist-item',
        TEAM_MEMBER: 'surgery-team-member',
        EQUIPMENT_ITEM: 'surgery-equipment-item',
        TIMELINE_STAGE: 'surgery-timeline-stage',
        INTRAOP_UPDATE: 'surgery-intraop-update',
        POSTOP_UPDATE: 'surgery-postop-update',
        DISCHARGE: 'surgery-discharge',
        PATIENT_SUMMARY: 'surgery-patient-summary'
    },
    INSURANCE_CLAIMS: {
        CLAIMS_SEARCH: 'insurance-claims-search',
        CLAIM_DETAIL: 'insurance-claim-detail',
        CLAIM_CREATE: 'insurance-claim-create',
        CLAIM_UPDATE: 'insurance-claim-update',
        CLAIM_SUBMIT: 'insurance-claim-submit',
        CLAIM_APPROVE: 'insurance-claim-approve',
        CLAIM_REJECT: 'insurance-claim-reject',
        CLAIM_APPEAL: 'insurance-claim-appeal',
        CLAIM_SETTLE: 'insurance-claim-settle',
        UPLOAD: 'insurance-claim-upload',
        PROVIDERS_TREE: 'insurance-providers-tree',
        STATS: 'insurance-claims-stats',
        TIMELINE: 'insurance-claim-timeline',
        NOTES: 'insurance-claim-notes',
        COMMUNICATION: 'insurance-claim-communication',
        AUDIT_LOGS: 'insurance-claim-audit-logs'
    },
    CASHIER: {
        DASHBOARD: 'cashier-dashboard',
        INVOICES_SEARCH: 'cashier-invoices-search',
        INVOICE_DETAIL: 'cashier-invoice-detail',
        PAYMENT: 'cashier-payment',
        REFUND: 'cashier-refund',
        DISCOUNT: 'cashier-discount',
        INSURANCE: 'cashier-insurance',
        VOID: 'cashier-void',
        PAYMENT_HISTORY: 'cashier-payment-history',
        PATIENTS_SEARCH: 'cashier-patients-search',
        EXPORT: 'cashier-export',
        PRINT_INVOICE: 'cashier-print-invoice',
        PRINT_RECEIPT: 'cashier-print-receipt'
    },
    RETAIL_POS: {
        CATALOG_SEARCH: 'retail-pos-catalog-search',
        CATALOG_BARCODE: 'retail-pos-catalog-barcode',
        CATALOG_DETAIL: 'retail-pos-catalog-detail',
        CATALOG_SUGGESTIONS: 'retail-pos-catalog-suggestions',
        CATEGORIES: 'retail-pos-categories',
        INSIGHT: 'retail-pos-insight',
        CARTS: 'retail-pos-carts',
        CREATE_CART: 'retail-pos-create-cart',
        UPSERT_CART: 'retail-pos-upsert-cart',
        REMOVE_CART: 'retail-pos-remove-cart',
        ATTACH_CUSTOMER: 'retail-pos-attach-customer',
        SUSPEND_CART: 'retail-pos-suspend-cart',
        RESUME_CART: 'retail-pos-resume-cart',
        PATIENTS_SEARCH: 'retail-pos-patients-search',
        CHECKOUT: 'retail-pos-checkout'
    },
    RADIOLOGY: {
        STATS: 'radiology-stats',
        TRENDS: 'radiology-trends',
        ALERTS: 'radiology-alerts',
        ACKNOWLEDGE: 'radiology-acknowledge',
        ORDERS_SEARCH: 'radiology-orders-search',
        SCHEDULE_SEARCH: 'radiology-schedule-search',
        SCHEDULE_RESCHEDULE: 'radiology-schedule-reschedule',
        SCHEDULE_CANCEL: 'radiology-schedule-cancel',
        SCHEDULE_REASSIGN: 'radiology-schedule-reassign',
        QUEUE: 'radiology-queue',
        QUEUE_ADVANCE: 'radiology-queue-advance',
        STUDIES_SEARCH: 'radiology-studies-search',
        STUDY_DETAIL: 'radiology-study-detail',
        REPORT_DETAIL: 'radiology-report-detail',
        REPORT_SAVE: 'radiology-report-save',
        REPORT_TEMPLATES: 'radiology-report-templates',
        REPORT_APPROVE: 'radiology-report-approve',
        REPORT_REJECT: 'radiology-report-reject',
        REPORT_RETURN_FOR_REVISION: 'radiology-report-return-for-revision',
        PATIENT_SUMMARY: 'radiology-patient-summary',
        PATIENT_HISTORY: 'radiology-patient-history'
    },
    NURSING: {
        ASSIGNMENTS: 'nursing-assignment',
        STATS: 'nursing-stats',
        ALERTS: 'nursing-alerts',
        ACKNOWLEDGE: 'nursing-acknowledge',
        PATIENT: 'nursing-patient',
        VITALS: 'nursing-vitals',
        VITAL_ADD: 'nursing-vital-add',
        MAR: 'nursing-mar',
        MAR_UPDATE: 'nursing-mar-update',
        IO: 'nursing-io',
        IO_ADD: 'nursing-io-add',
        TASKS: 'nursing-tasks',
        TASK_UPDATE: 'nursing-task-update',
        NOTES: 'nursing-notes',
        NOTE_ADD: 'nursing-note-add',
        HANDOVER: 'nursing-handover',
        HANDOVER_ACKNOWLEDGE: 'nursing-handover-acknowledge'
    },
    MEDICAL_RECORD: {
        CONTEXT: 'medical-record-context',
        SNAPSHOT: 'medical-record-snapshot',
        DEMOGRAPHICS: 'medical-record-demographics',
        HISTORY: 'medical-record-history',
        ALLERGIES: 'medical-record-allergies',
        ENCOUNTERS: 'medical-record-encounters',
        DIAGNOSES: 'medical-record-diagnoses',
        PRESCRIPTIONS: 'medical-record-prescriptions',
        LAB: 'medical-record-lab',
        IMAGING: 'medical-record-imaging',
        NOTES: 'medical-record-notes',
        BILLING: 'medical-record-billing'
    },
    LABORATORY: {
        STATS: 'laboratory-stats',
        TRENDS: 'laboratory-trends',
        ALERTS: 'laboratory-alerts',
        ALERT_ACKNOWLEDGE: 'laboratory-alert-acknowledge',
        ORDERS: 'laboratory-orders',
        SAMPLES: 'laboratory-samples',
        SAMPLES_COLLECT: 'laboratory-samples-collect',
        SAMPLES_RECOLLECT: 'laboratory-samples-recollect',
        SAMPLES_REJECT: 'laboratory-samples-reject',
        RESULTS_SEARCH: 'laboratory-results-search',
        RESULT_UPDATE: 'laboratory-result-update',
        RESULT_APPROVE: 'laboratory-result-approve',
        RESULT_REJECT: 'laboratory-result-reject',
        RESULT_RETURN_FOR_REVIEW: 'laboratory-result-return-for-review',
        PATIENT_SUMMARY: 'laboratory-patient-summary',
        PATIENT_HISTORY: 'laboratory-patient-history'
    },
    INVENTORY: {
        KPIS: 'inventory-kpis',
        QUICK_CATEGORIES: 'inventory-quick-categories',
        MEDICINES_SEARCH: 'inventory-medicines-search',
        MEDICINE_BARCODE: 'inventory-medicine-barcode',
        MEDICINE_DETAIL: 'inventory-medicine-detail',
        MEDICINE_BATCHES: 'inventory-medicine-batches',
        BATCH_RECEIVE: 'inventory-batch-receive',
        BATCH_TRANSFER: 'inventory-batch-transfer',
        BATCH_ADJUST: 'inventory-batch-adjust',
        BATCH_RESERVE: 'inventory-batch-reserve',
        BATCH_LOCK: 'inventory-batch-lock',
        BATCH_DISPOSE: 'inventory-batch-dispose',
        BATCH_BARCODE: 'inventory-batch-barcode',
        WAREHOUSE_ZONES: 'inventory-warehouse-zones',
        INTELLIGENCE: 'inventory-intelligence',
        MOVEMENTS: 'inventory-movements',
        ALERTS: 'inventory-alerts',
        ALERT_ACKNOWLEDGE: 'inventory-alert-acknowledge',
        MEDICINE_HISTORY: 'inventory-medicine-history'
    },
    STOCK_TAKE: {
        SEARCH: 'stock-take-search',
        DETAIL: 'stock-take-detail',
        CREATE: 'stock-take-create',
        UPDATE: 'stock-take-update',
        DELETE: 'stock-take-delete',
        START: 'stock-take-start',
        COMPLETE: 'stock-take-complete',
        APPROVE: 'stock-take-approve',
        REJECT: 'stock-take-reject',
        CANCEL: 'stock-take-cancel',
        ASSIGN: 'stock-take-assign',
        ITEMS: 'stock-take-items',
        ITEMS_UPDATE: 'stock-take-items-update',
        CATEGORIES: 'stock-take-categories',
        SUMMARY: 'stock-take-summary',
        HISTORY: 'stock-take-history',
        KPIS: 'stock-take-kpis',
        ACTIVITIES: 'stock-take-activities',
        EXPORT: 'stock-take-export',
        PRINT: 'stock-take-print',
        WAREHOUSES: 'stock-take-warehouses',
        USERS: 'stock-take-users'
    },
    DISPENSING: {
        QUEUE: 'dispensing-queue',
        STATS: 'dispensing-stats',
        WORKSPACE: 'dispensing-workspace',
        ALERT_ACKNOWLEDGE: 'dispensing-acknowledge',
        ITEM_UPDATE: 'dispensing-item-update',
        ITEM_REPLACE: 'dispensing-item-replace',
        ITEM_RESERVE: 'dispensing-item-reserve',
        ITEM_SCAN: 'dispensing-item-scan',
        MEDICINE_BATCHES: 'dispensing-medicine-batches',
        MEDICINE_DETAIL: 'dispensing-medicine-detail',
        HOLD: 'dispensing-hold',
        CANCEL: 'dispensing-cancel',
        COMPLETE: 'dispensing-complete'
    },
    DOCTOR_DESK: {
        SNAPSHOT: 'doctor-desk-snapshot'
    },
    PATIENT: {
        CREATE: 'patient-create'
    }
} as const;

type NestedValues<T> = T extends string ? T : T extends Record<string, unknown> ? NestedValues<T[keyof T]> : never;

export type LoadingKey = NestedValues<typeof LoadingKeys>;