export enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    NURSE = "NURSE",
    PHAMACIST = "PHAMACIST",
    CASHIER = "CASHIER",
    LAB_TECHNICIAN = "LAB_TECHNICIAN",
    RADIOLOGIST = "RADIOLOGIST",
    RECEPTIONIST = "RECEPTIONIST",
    ACCOUNTANT = "ACCOUNTANT",
    INVENTORY_MANAGER = "INVENTORY_MANAGER",
    IT_SUPPORT = "IT_SUPPORT",
    DOCTOR = "DOCTOR",
    PATIENT = "PATIENT"
}