export enum Role {
    SUPER_ADMIN,
    ADMIN,
    NURSE,
    PHAMACIST,
    CASHIER,
    LAB_TECHNICIAN,
    RADIOLOGIST,
    RECEPTIONIST,
    ACCOUNTANT,
    INVENTORY_MANAGER,
    IT_SUPPORT,
    DOCTOR,
    PATIENT
}