export const BASE_API = {
  VERSION: '/api/config/version',
  CONFIG: 'api/config',
  MENU: '/api/admin-menus/search',
  PROFILE: '/api/users/me',
  LOGIN: '/api/users/login',
  OAUTHLOGIN: '/api/users/oauth-login',
  LOGOUT: '/api/users/refresh/logout',
  REGISTER: '/api/users/register',
  REFRESHTOKEN: 'api/users/refresh/refresh-token',
  FORGOTPASSWORD: '/api/users/forgot-password',
  MEDICALSPECIALTY: {
    BASE: '/api/medical-specialties',
    SEARCH: '/api/medical-specialties/search'
  },
  APPOINTMENTTYPE: {
    BASE: '/api/appointment-types',
    SEARCH: '/api/appointment-types/search'
  },
  IMAGINGMODALITY: {
    BASE: '/api/imaging-modalities',
    SEARCH: '/api/imaging-modalities/search'
  },
  INSURANCECOMPANY: {
    BASE: '/api/insurance-companies',
    SEARCH: '/api/insurance-companies/search'
  },
  MANUFACTURER: {
    BASE: '/api/manufacturers',
    SEARCH: '/api/manufacturers/search'
  },
  MEDICINECATEGORY: {
    BASE: '/api/medicine-categories',
    SEARCH: '/api/medicine-categories/search'
  },
  SUPPLIER: {
    BASE: '/api/suppliers',
    SEARCH: '/api/suppliers/search'
  },
  LABTESTCATEGORY: {
    BASE: '/api/lab-test-categories',
    SEARCH: '/api/lab-test-categories/search',
    LOOKUP: '/api/lab-test-categories/lookup'
  },
  LABTEST: {
    BASE: '/api/lab-tests',
    SEARCH: '/api/lab-tests/search'
  },
  SEQUENCETRACKER: {
    BASE: '/api/sequence-trackers',
    SEARCH: '/api/sequence-trackers/search'
  },
  DOCTOR: {
    BASE: '/api/doctors',
    SEARCH: '/api/doctors/search'
  },
  ARTICLE: {
    BASE: '/api/articles',
    SEARCH: '/api/articles/search'
  },
  ADMINMENU: {
    BASE: '/api/admin-menus',
    SEARCH: '/api/admin-menus/search',
    MINE: '/api/admin-menus/mine'
  },
  HOSPITALGROUP: {
    BASE: '/api/hospital-groups',
    SEARCH: '/api/hospital-groups/search'
  },
  HOSPITAL: {
    BASE: '/api/hospitals',
    SEARCH: '/api/hospitals/search'
  },
  DEPARTMENT: {
    BASE: '/api/departments',
    SEARCH: '/api/departments/search'
  },
  HOME_BANNER: {
    BASE: '/api/home-banners',
    SEARCH: '/api/home-banners/search'
  },
  HOME_FEATURE: {
    BASE: '/api/home-features',
    SEARCH: '/api/home-features/search'
  },
  HOME_TESTIMONIAL: {
    BASE: '/api/home-testimonials',
    SEARCH: '/api/home-testimonials/search'
  },
  HOME_SETTINGS: {
    BASE: '/api/home-settings'
  },
  PATIENT: {
    BASE: '/api/patients',
    SEARCH: '/api/patients/search'
  },
  CAMPAIGN: {
    BASE: '/api/campaigns',
    SEARCH: '/api/campaigns/search',
    STATS: '/api/campaigns/stats',
  },
  LEAD: {
    BASE: '/api/leads',
    SEARCH: '/api/leads/search',
    STATS: '/api/leads/stats',
  },
  COMPLAINT: {
    BASE: '/api/complaints',
    SEARCH: '/api/complaints/search',
    STATS: '/api/complaints/stats',
  },
  AUDIENCE_SEGMENT: {
    LOOKUP: '/api/audience-segments/lookup',
  },
  MEDICAL_RECORD: {
    CONTEXT:       (patientId: string) => `/api/medical-records/${patientId}/context`,
    SNAPSHOT:      (patientId: string) => `/api/medical-records/${patientId}/snapshot`,
    DEMOGRAPHICS: (patientId: string) => `/api/medical-records/${patientId}/demographics`,
    HISTORY:       (patientId: string) => `/api/medical-records/${patientId}/history`,
    ALLERGIES:     (patientId: string) => `/api/medical-records/${patientId}/allergies`,
    ENCOUNTERS:    (patientId: string) => `/api/medical-records/${patientId}/encounters`,
    DIAGNOSES:     (patientId: string) => `/api/medical-records/${patientId}/diagnoses`,
    PRESCRIPTIONS: (patientId: string) => `/api/medical-records/${patientId}/prescriptions`,
    LAB:           (patientId: string) => `/api/medical-records/${patientId}/lab`,
    IMAGING:       (patientId: string) => `/api/medical-records/${patientId}/imaging`,
    NOTES:         (patientId: string) => `/api/medical-records/${patientId}/notes`,
    BILLING:       (patientId: string) => `/api/medical-records/${patientId}/billing`,
  },
  MEDICAL_SERVICE: {
    BASE: '/api/medical-services',
    SEARCH: '/api/medical-services/search',
    STATS: '/api/medical-services/stats',
    ARCHIVE: (id: string) => `/api/medical-services/${id}/archive`,
    RESTORE: (id: string) => `/api/medical-services/${id}/restore`,
    PUBLISH: (id: string) => `/api/medical-services/${id}/publish`,
    DUPLICATE: (id: string) => `/api/medical-services/${id}/duplicate`,
    BULK_ARCHIVE: '/api/medical-services/bulk/archive',
    BULK_DELETE: '/api/medical-services/bulk/delete',
    EXPORT: '/api/medical-services/export',
  },
  USER: {
    BASE: '/api/users',
    SEARCH: '/api/users/search',
    SEARCH_BY_ID: '/api/users/me',
    REGISTER: '/api/users/register',
    ASSIGN_ROLE: '/api/users/assign-role-to-user',
    CHECK_AUTH: '/api/users/check-auth',
    GET_USER_DATA: '/api/users/me/data',
  },
  ROLE: {
    BASE: '/api/roles',
    SEARCH: '/api/roles/search',
    CREATE: '/api/roles/create',
    ASSIGN_PERMISSION: '/api/roles/assign-permission-to-role'
  },
  PERMISSION: {
    BASE: '/api/permissions',
    SEARCH: '/api/permissions/search',
    CREATE: '/api/permissions/create',
  },
  PREFERENCE: {
    BASE: '/api/user-preferences',
    ME: '/api/users/me/preferences',
  },
  PRESCRIPTION_RX: {
    DRAFT: (id: string) => `/api/prescriptions/${id}`,
    CREATE: '/api/prescriptions',
    UPDATE: (id: string) => `/api/prescriptions/${id}`,
    ISSUE: (id: string) => `/api/prescriptions/${id}/issue`,
    CANCEL: (id: string) => `/api/prescriptions/${id}/cancel`,
    MEDICINE_SEARCH: '/api/medicines',
    CDS_CHECK: '/api/prescriptions/cds-check',
    COST_ESTIMATE: (id: string) => `/api/prescriptions/${id}/cost-estimate`,
    RECENT: (patientId: string) => `/api/patients/${patientId}/prescriptions/recent`,
    FAVORITES: (doctorId: string) => `/api/doctors/${doctorId}/favorite-medications`,
    TEMPLATES: (doctorId: string) => `/api/prescription-templates?doctorId=${doctorId}`,
  },
  BED_MAP: {
    WARDS: '/api/bed-map/wards',
    SNAPSHOT: '/api/bed-map/snapshot',
    STATS: '/api/bed-map/stats',
    BEDS: '/api/bed-map/beds',
    SEARCH: '/api/bed-map/beds/search',
    BED_BY_ID: (bedId: string) => `/api/bed-map/beds/${bedId}`,
    ASSIGN: (bedId: string) => `/api/bed-map/beds/${bedId}/assign`,
    DISCHARGE: (bedId: string) => `/api/bed-map/beds/${bedId}/discharge`,
    HISTORY: (bedId: string) => `/api/bed-map/beds/${bedId}/history`,
  },
  PRINT_TEMPLATE: {
    BASE: '/api/print-templates',
    SEARCH: '/api/print-templates/search',
    RENDER: '/api/print-templates/render',
    PLACEHOLDERS: '/api/print-templates/placeholders',
  },
  NURSING: {
    ASSIGNMENTS: '/api/nursing/assignments',
    STATS: '/api/nursing/stats',
    ALERTS: '/api/nursing/alerts',
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/nursing/alerts/${alertId}/acknowledge`,
    PATIENT: (patientId: string) => `/api/nursing/patients/${patientId}`,
    VITALS: (patientId: string) => `/api/nursing/patients/${patientId}/vitals`,
    MAR: (patientId: string) => `/api/nursing/patients/${patientId}/mar`,
    MAR_UPDATE: (marEntryId: string) => `/api/nursing/mar/${marEntryId}`,
    IO: (patientId: string) => `/api/nursing/patients/${patientId}/io`,
    TASKS: (patientId: string) => `/api/nursing/patients/${patientId}/tasks`,
    TASK_UPDATE: (taskId: string) => `/api/nursing/tasks/${taskId}`,
    NOTES: (patientId: string) => `/api/nursing/patients/${patientId}/notes`,
    HANDOVER: '/api/nursing/handover',
    HANDOVER_ACKNOWLEDGE: (cardId: string) => `/api/nursing/handover/${cardId}/acknowledge`,
  },
  TREATMENT_SHEET: {
    SUMMARY: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/summary`,
    STATS: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/stats`,
    ALERTS: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/alerts`,
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/treatment-sheet/alerts/${alertId}/acknowledge`,
    TIMELINE: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/timeline`,
    ORDERS: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/orders`,
    ORDER_UPDATE: (orderId: string) => `/api/treatment-sheet/orders/${orderId}`,
    MEDICATIONS: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/medications`,
    MEDICATION_UPDATE: (entryId: string) => `/api/treatment-sheet/medications/${entryId}`,
    PROCEDURES: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/procedures`,
    LABS: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/labs`,
    IMAGING: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/imaging`,
    NOTES: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/notes`,
    EXPORT: (patientId: string) => `/api/treatment-sheet/patients/${patientId}/export`,
  },
  LABORATORY: {
    STATS: '/api/laboratory/stats',
    TRENDS: '/api/laboratory/trends',
    ALERTS: '/api/laboratory/alerts',
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/laboratory/alerts/${alertId}/acknowledge`,
    ORDERS_SEARCH: '/api/laboratory/orders/search',
    ORDER_DETAIL: (orderId: string) => `/api/laboratory/orders/${orderId}`,
    ORDERS_BULK_STATUS: '/api/laboratory/orders/bulk-status',
    SAMPLES_SEARCH: '/api/laboratory/samples/search',
    SAMPLE_COLLECT: (sampleId: string) => `/api/laboratory/samples/${sampleId}/collect`,
    SAMPLE_RECOLLECT: (sampleId: string) => `/api/laboratory/samples/${sampleId}/recollect`,
    SAMPLE_REJECT: (sampleId: string) => `/api/laboratory/samples/${sampleId}/reject`,
    SAMPLE_TIMELINE: (sampleId: string) => `/api/laboratory/samples/${sampleId}/timeline`,
    SAMPLE_BARCODE: (sampleId: string) => `/api/laboratory/samples/${sampleId}/barcode`,
    RESULTS_SEARCH: '/api/laboratory/results/search',
    RESULT_UPDATE: (resultId: string) => `/api/laboratory/results/${resultId}`,
    RESULT_APPROVE: (resultId: string) => `/api/laboratory/results/${resultId}/approve`,
    RESULT_REJECT: (resultId: string) => `/api/laboratory/results/${resultId}/reject`,
    RESULT_RETURN_FOR_REVIEW: (resultId: string) => `/api/laboratory/results/${resultId}/return-for-review`,
    PATIENT_SUMMARY: (patientId: string) => `/api/laboratory/patients/${patientId}/summary`,
    PATIENT_HISTORY: (patientId: string) => `/api/laboratory/patients/${patientId}/history`,
    ORDER_EXPORT: (orderId: string) => `/api/laboratory/orders/${orderId}/export`,
    SAVED_FILTERS: '/api/laboratory/saved-filters',
  },
  CASHIER: {
    DASHBOARD: '/api/cashier/dashboard',
    INVOICES: '/api/cashier/invoices',
    INVOICE_DETAIL: (invoiceId: string) => `/api/cashier/invoices/${invoiceId}`,
    PAYMENTS: '/api/cashier/payments',
    REFUNDS: '/api/cashier/refunds',
    DISCOUNTS: (invoiceId: string) => `/api/cashier/invoices/${invoiceId}/discounts`,
    INSURANCE: (invoiceId: string) => `/api/cashier/invoices/${invoiceId}/insurance`,
    VOID: (invoiceId: string) => `/api/cashier/invoices/${invoiceId}/void`,
    PAYMENT_HISTORY: '/api/cashier/payment-history',
    PATIENTS_SEARCH: '/api/patients/search',
    PAYMENT_METHODS: '/api/payment-methods',
    EXPORT: '/api/cashier/export',
    PRINT_INVOICE: '/api/cashier/print-invoice',
    PRINT_RECEIPT: '/api/cashier/print-receipt',
  },
  PHARMACY_RETAIL: {
    CATALOG_SEARCH: '/api/pharmacy/retail/catalog/search',
    CATALOG_BARCODE: (code: string) => `/api/pharmacy/retail/catalog/barcode/${code}`,
    CATALOG_DETAIL: (medicineId: string) => `/api/pharmacy/retail/catalog/${medicineId}`,
    CATALOG_SUGGESTIONS: (mode: string) => `/api/pharmacy/retail/catalog/suggestions?mode=${mode}`,
    INSIGHT: '/api/pharmacy/retail/insight',
    CARTS: '/api/pharmacy/retail/carts',
    CART_ITEM: (cartId: string, medicineId: string) => `/api/pharmacy/retail/carts/${cartId}/items/${medicineId}`,
    CART_ITEM_REMOVE: (cartId: string, lineItemId: string) => `/api/pharmacy/retail/carts/${cartId}/items/${lineItemId}`,
    CART_CUSTOMER: (cartId: string) => `/api/pharmacy/retail/carts/${cartId}/customer`,
    CART_SUSPEND: (cartId: string) => `/api/pharmacy/retail/carts/${cartId}/suspend`,
    CART_RESUME: (cartId: string) => `/api/pharmacy/retail/carts/${cartId}/resume`,
    CART_CHECKOUT: (cartId: string) => `/api/pharmacy/retail/carts/${cartId}/checkout`,
    CART_WARNINGS: (cartId: string) => `/api/pharmacy/retail/cart/${cartId}/warnings`,
    PATIENTS_SEARCH: '/api/pharmacy/retail/patients/search',
    TRANSACTION_DETAIL: (transactionId: string) => `/api/pharmacy/retail/transactions/${transactionId}`,
    TRANSACTION_REFUND: (transactionId: string) => `/api/pharmacy/retail/transactions/${transactionId}/refund`,
    TRANSACTION_RECEIPT: (transactionId: string) => `/api/pharmacy/retail/transactions/${transactionId}/receipt`,
    TRANSACTION_RECEIPT_EMAIL: (transactionId: string) => `/api/pharmacy/retail/transactions/${transactionId}/receipt/email`,
    TRANSACTION_RECEIPT_SMS: (transactionId: string) => `/api/pharmacy/retail/transactions/${transactionId}/receipt/sms`,
  },
  DISPENSING: {
    QUEUE: '/api/pharmacy/dispensing/queue',
    WORKSPACE: (queueId: string) => `/api/pharmacy/dispensing/queue/${queueId}/workspace`,
    ALERT_ACKNOWLEDGE: (workspaceId: string, alertId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/alerts/${alertId}/acknowledge`,
    ITEM_UPDATE: (workspaceId: string, itemId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/items/${itemId}`,
    ITEM_REPLACE: (workspaceId: string, itemId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/items/${itemId}/replace`,
    ITEM_RESERVE: (workspaceId: string, itemId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/items/${itemId}/reserve`,
    ITEM_SCAN: (workspaceId: string, itemId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/items/${itemId}/scan`,
    MEDICINE_BATCHES: (medicineId: string) => `/api/pharmacy/dispensing/medicines/${medicineId}/batches`,
    MEDICINE_DETAIL: (medicineId: string) => `/api/pharmacy/dispensing/medicines/${medicineId}/detail`,
    HOLD: (workspaceId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/hold`,
    CANCEL: (workspaceId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/cancel`,
    COMPLETE: (workspaceId: string) => `/api/pharmacy/dispensing/workspace/${workspaceId}/complete`,
    STATS: '/api/pharmacy/dispensing/stats',
  },
  INVENTORY: {
    KPIS: '/api/pharmacy/inventory/kpis',
    MEDICINES_SEARCH: '/api/pharmacy/inventory/medicines/search',
    MEDICINE_BARCODE: (code: string) => `/api/pharmacy/inventory/medicines/barcode/${code}`,
    MEDICINE_DETAIL: (medicineId: string) => `/api/pharmacy/inventory/medicines/${medicineId}`,
    MEDICINE_BATCHES: (medicineId: string) => `/api/pharmacy/inventory/medicines/${medicineId}/batches`,
    MEDICINE_HISTORY: (medicineId: string) => `/api/pharmacy/inventory/medicines/${medicineId}/history`,
    WAREHOUSE_ZONES: '/api/pharmacy/inventory/warehouse/zones',
    INTELLIGENCE: '/api/pharmacy/inventory/intelligence',
    MOVEMENTS: '/api/pharmacy/inventory/movements',
    ALERTS: '/api/pharmacy/inventory/alerts',
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/pharmacy/inventory/alerts/${alertId}/acknowledge`,
    BATCH_RECEIVE: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/receive`,
    BATCH_TRANSFER: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/transfer`,
    BATCH_ADJUST: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/adjust`,
    BATCH_RESERVE: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/reserve`,
    BATCH_LOCK: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/lock`,
    BATCH_DISPOSE: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/dispose`,
    BATCH_BARCODE: (batchId: string) => `/api/pharmacy/inventory/batches/${batchId}/barcode`,
  },
  STOCK_TAKE: {
    SEARCH: '/api/stock-takes/search',
    BASE: '/api/stock-takes',
    DETAIL: (id: string) => `/api/stock-takes/${id}`,
    START: (id: string) => `/api/stock-takes/${id}/start`,
    COMPLETE: (id: string) => `/api/stock-takes/${id}/complete`,
    APPROVE: (id: string) => `/api/stock-takes/${id}/approve`,
    REJECT: (id: string) => `/api/stock-takes/${id}/reject`,
    CANCEL: (id: string) => `/api/stock-takes/${id}/cancel`,
    ASSIGN: (id: string) => `/api/stock-takes/${id}/assign`,
    ITEMS: (id: string) => `/api/stock-takes/${id}/items`,
    CATEGORIES: (id: string) => `/api/stock-takes/${id}/categories`,
    SUMMARY: (id: string) => `/api/stock-takes/${id}/summary`,
    HISTORY: (id: string) => `/api/stock-takes/${id}/history`,
    KPIS: '/api/stock-takes/kpis',
    ACTIVITIES: '/api/stock-takes/activities',
    EXPORT: '/api/stock-takes/export',
    PRINT: (id: string) => `/api/stock-takes/${id}/print`,
  },
  SURGERY: {
    STATS: '/api/surgery/stats',
    TRENDS: '/api/surgery/trends',
    ALERTS: '/api/surgery/alerts',
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/surgery/alerts/${alertId}/acknowledge`,
    CASES_SEARCH: '/api/surgery/cases/search',
    CASE_DETAIL: (surgeryId: string) => `/api/surgery/cases/${surgeryId}`,
    CASE_CREATE: '/api/surgery/cases',
    CASE_CANCEL: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/cancel`,
    ROOMS: '/api/surgery/rooms',
    ROOM_STATUS: (roomId: string) => `/api/surgery/rooms/${roomId}/status`,
    CHECKLIST: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/checklist`,
    CHECKLIST_ITEM: (surgeryId: string, itemId: string) => `/api/surgery/cases/${surgeryId}/checklist/${itemId}`,
    TEAM: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/team`,
    TEAM_MEMBER: (surgeryId: string, memberId: string) => `/api/surgery/cases/${surgeryId}/team/${memberId}`,
    EQUIPMENT: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/equipment`,
    EQUIPMENT_ITEM: (surgeryId: string, itemId: string) => `/api/surgery/cases/${surgeryId}/equipment/${itemId}`,
    TIMELINE_STAGE: (surgeryId: string, stage: string) => `/api/surgery/cases/${surgeryId}/timeline/${stage}`,
    INTRAOP_UPDATE: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/intraop`,
    POSTOP_UPDATE: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/postop`,
    DISCHARGE: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/discharge`,
    PATIENT_SUMMARY: (patientId: string) => `/api/surgery/patients/${patientId}/summary`,
    CONSENT_PRINT: (surgeryId: string) => `/api/surgery/cases/${surgeryId}/consent/print`,
    SAVED_FILTERS: '/api/surgery/saved-filters',
  },
  INSURANCE_CLAIMS: {
    CLAIMS_SEARCH: '/api/insurance/claims',
    CLAIM_DETAIL: (claimId: string) => `/api/insurance/claims/${claimId}`,
    CLAIM_CREATE: '/api/insurance/claims',
    CLAIM_UPDATE: (claimId: string) => `/api/insurance/claims/${claimId}`,
    CLAIM_SUBMIT: (claimId: string) => `/api/insurance/claims/${claimId}/submit`,
    CLAIM_APPROVE: (claimId: string) => `/api/insurance/claims/${claimId}/approve`,
    CLAIM_REJECT: (claimId: string) => `/api/insurance/claims/${claimId}/reject`,
    CLAIM_APPEAL: (claimId: string) => `/api/insurance/claims/${claimId}/appeal`,
    CLAIM_SETTLE: (claimId: string) => `/api/insurance/claims/${claimId}/settle`,
    UPLOAD: '/api/insurance/upload',
    PROVIDERS: '/api/insurance/providers',
    PROVIDERS_TREE: '/api/insurance/providers/tree',
    PATIENTS_SEARCH: '/api/patients/search',
    STATS: '/api/insurance/claims/stats',
    TIMELINE: (claimId: string) => `/api/insurance/claims/${claimId}/timeline`,
    NOTES: (claimId: string) => `/api/insurance/claims/${claimId}/notes`,
    COMMUNICATION: (claimId: string) => `/api/insurance/claims/${claimId}/communication`,
    AUDIT_LOGS: (claimId: string) => `/api/insurance/claims/${claimId}/audit-logs`,
    SAVED_SEARCHES: '/api/insurance/saved-searches',
  },
  RADIOLOGY: {
    STATS: '/api/radiology/stats',
    TRENDS: '/api/radiology/trends',
    ALERTS: '/api/radiology/alerts',
    ALERT_ACKNOWLEDGE: (alertId: string) => `/api/radiology/alerts/${alertId}/acknowledge`,
    ORDERS_SEARCH: '/api/radiology/orders/search',
    ORDER_DETAIL: (orderId: string) => `/api/radiology/orders/${orderId}`,
    ORDERS_BULK_STATUS: '/api/radiology/orders/bulk-status',
    SCHEDULE_SEARCH: '/api/radiology/schedule/search',
    SCHEDULE_RESCHEDULE: (slotId: string) => `/api/radiology/schedule/${slotId}/reschedule`,
    SCHEDULE_CANCEL: (slotId: string) => `/api/radiology/schedule/${slotId}/cancel`,
    SCHEDULE_REASSIGN: (slotId: string) => `/api/radiology/schedule/${slotId}/reassign`,
    QUEUE: '/api/radiology/queue',
    QUEUE_ADVANCE: (entryId: string) => `/api/radiology/queue/${entryId}/advance`,
    STUDY_DETAIL: (studyId: string) => `/api/radiology/studies/${studyId}`,
    STUDIES_SEARCH: '/api/radiology/studies/search',
    REPORT_DETAIL: (orderId: string) => `/api/radiology/reports/${orderId}`,
    REPORT_TEMPLATES: '/api/radiology/report-templates',
    REPORT_APPROVE: (orderId: string) => `/api/radiology/reports/${orderId}/approve`,
    REPORT_REJECT: (orderId: string) => `/api/radiology/reports/${orderId}/reject`,
    REPORT_RETURN_FOR_REVISION: (orderId: string) => `/api/radiology/reports/${orderId}/return-for-revision`,
    PATIENT_SUMMARY: (patientId: string) => `/api/radiology/patients/${patientId}/summary`,
    PATIENT_HISTORY: (patientId: string) => `/api/radiology/patients/${patientId}/history`,
    ORDER_EXPORT: (orderId: string) => `/api/radiology/orders/${orderId}/export`,
    SAVED_FILTERS: '/api/radiology/saved-filters',
  },
  REVENUE_REPORT: {
    SUMMARY: '/api/revenue-report/summary',
    TREND: '/api/revenue-report/trend',
    PAYMENT_METHODS: '/api/revenue-report/payment-methods',
    DEPARTMENTS: '/api/revenue-report/departments',
    DOCTORS: '/api/revenue-report/doctors',
    INSURANCE: '/api/revenue-report/insurance',
    OUTSTANDING_SUMMARY: '/api/revenue-report/outstanding/summary',
    OUTSTANDING_SEARCH: '/api/revenue-report/outstanding/search',
    REFUNDS_SEARCH: '/api/revenue-report/refunds/search',
    DISCOUNTS_SEARCH: '/api/revenue-report/discounts/search',
    TRANSACTIONS_SEARCH: '/api/revenue-report/transactions/search',
    TRANSACTION_DETAIL: (id: string) => `/api/revenue-report/transactions/${id}`,
    EXPORT: '/api/revenue-report/export',
  },
  DASHBOARD: {
    OVERVIEW: '/api/dashboard/overview',
    ALERT_DISMISS: (alertId: string) => `/api/dashboard/alerts/${alertId}/dismiss`,
    EXPORT: '/api/dashboard/export',
  },
};
