using PhysioBoo.Domain.Entities.PatientInformation;

namespace PhysioBoo.Domain.Entities.Inpatient
{
    // SBAR handover for one admitted patient at the end of one shift. Generated by the server.
    public class HandoverCard : TenantEntity
    {
        #region Core HandoverCard Table (12)
        public Guid AdmissionId { get; private set; }
        public Guid PatientId { get; private set; }
        public DateOnly ShiftDate { get; private set; }
        public ShiftCode OutgoingShift { get; private set; }
        public ShiftCode IncomingShift { get; private set; }
        public string Situation { get; private set; }
        public string Background { get; private set; }
        public string Assessment { get; private set; }
        public string Recommendation { get; private set; }
        public bool IsAcknowledged { get; private set; }
        public string? AcknowledgedByName { get; private set; }
        public DateTime? AcknowledgedAt { get; private set; }

        public virtual Admission? Admission { get; private set; }
        public virtual Patient? Patient { get; private set; }
        #endregion

        #region Constructor (12)
        public HandoverCard(
            Guid id,
            Guid admissionId,
            Guid patientId,
            DateOnly shiftDate,
            ShiftCode outgoingShift,
            ShiftCode incomingShift,
            string situation,
            string background,
            string assessment,
            string recommendation
        ) : base(id)
        {
            AdmissionId = admissionId;
            PatientId = patientId;
            ShiftDate = shiftDate;
            OutgoingShift = outgoingShift;
            IncomingShift = incomingShift;
            Situation = situation;
            Background = background;
            Assessment = assessment;
            Recommendation = recommendation;
            IsAcknowledged = false;
        }
        #endregion

        #region Setter Methods (12)
        public void SetSituation(string situation) { Situation = situation; }
        public void SetBackground(string background) { Background = background; }
        public void SetAssessment(string assessment) { Assessment = assessment; }
        public void SetRecommendation(string recommendation) { Recommendation = recommendation; }
        public void SetIsAcknowledged(bool isAcknowledged) { IsAcknowledged = isAcknowledged; }
        public void SetAcknowledgedByName(string? acknowledgedByName) { AcknowledgedByName = acknowledgedByName; }
        public void SetAcknowledgedAt(DateTime? acknowledgedAt) { AcknowledgedAt = acknowledgedAt; }
        #endregion
    }
}
